### PR TITLE
Add pytorch implementation of Perceptual Losses for Style Transfer and Super Resolution

### PR DESCRIPTION
**Pull request by ris27hav**

### CODE REVIEW

**Comment by SomTambe** [comment]
Great PR! Merging it right away!

**Comment by SomTambe** [comment]
Okay sorry one more thing - can you rename the folder to `PyTorch` instead of `Pytorch` and create another PR? Just that small change, sorry I should have seen it.

**Comment by ris27hav** [comment]
Should I name the folder PerceptualLossesForStyleTransferAndSuperResolution_PyTorch?
i.e. add Style Transfer as well. It felt too big.

**Comment by SomTambe** [comment]
Yes that sounds good to me.

**Comment by ris27hav** [comment]
Done

**Pull request merged**
