### PR TITLE
Adding pytorch model: deep visual semantic alignments image captioning

### PR DESCRIPTION
**Pull request by gurbaaz27**
A small problem working with test.py will be soon resolved. Rest works just fine.

### CODE REVIEW

**Comment by namangup** [comment]
@gurbaaz27  I was working on this. You didn't message on messenger as I checked.

**Comment by gurbaaz27** [comment]
@namangup I saw all the messenger messages and when I read yours I thought you changed to "very deep super-resolution" model! It has a big name so I didn't read whole. I believe the fault is mine but now if you haven't completed you can work on a similar topic, or either way, do one some other dataset. Sorry :( . Let me know what u decide.

**Comment by namangup** [comment]
No problem , I'll switch to another one.

**Comment by nirmal-suthar** [comment]
> A small problem working with test.py will be soon resolved. Rest works just fine.

comment here, once you are done with test.py.

**Pull request merged**
