### PR TITLE
Add MobileNet_V1 implemented in Tensorflow

### PR DESCRIPTION
**Pull request by Rajarshi1001**
Implementation of mobilenet_v1.

### CODE REVIEW

**Comment by AthaSSiN** [comment]
1. Edit pull request title to display the name of the model and your framework.
2. Documentation is proper.
3. Explain the purpose of the functions that you have created using comments wherever possible, for better understanding.
4. Remove unnecessary imports (which are not being used). For eg. in evaluate.py, pyplot and other libraries are not being used.
5. Remove the commented code lines which are not being used, unless they are necessary to explain the code (reduced readability). For example in dataloader.py and model.py

**Comment by AthaSSiN** [comment]
@Rajarshi1001 Don't make changes directly on github, use git to do that from the next time. There are a lot of unnecessary commits if you edit straight on github.

**Comment by Rajarshi1001** [comment]
> @Rajarshi1001 Don't make changes directly on github, use git to do that from the next time. There are a lot of unnecessary commits if you edit straight on github.

Yes the readme was edited several times due to minor typos.

**Comment by namangup** [comment]
LGTM. Change the directory name to MobileNet_v1_TF

**Comment by Rajarshi1001** [comment]
> LGTM. Change the directory name to MobileNet_v1_TF

Done.

**Pull request merged**
